"use client";

import type { Metadata } from "next";
import "./globals.css";
import React, { ReactElement } from "react";
import { StyledEngineProvider, ThemeProvider, createTheme } from "@mui/material";
import { customTypography } from "@/themes/typography";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactElement }): ReactElement {
  const customTheme = createTheme({
    typography: customTypography,
  });

  //////////////////////////////////////////////////////////////////////////////////////////////////////
  return (
    <StyledEngineProvider>
      <ThemeProvider theme={customTheme}>
        <html lang='en'>
          <body suppressHydrationWarning={true}>{children}</body>
        </html>
      </ThemeProvider>
    </StyledEngineProvider>
  );
}
